# Apply SAM modes from ISODISTORT output file directly to a supercell structure

In [1]:
import numpy as np

def matrix_to_string(matrix):
    # Converting each row of the matrix to a string
    row_strings = [" ".join(f"{value:.16f}" for value in row) for row in matrix]

    # Joining all row strings with a newline character
    return "\n".join(row_strings)

def string_to_matrix(string):
    string = [list(map(float, row.split())) for row in string.strip().split('\n')]

    # Converting the data to a NumPy matrix
    return np.array(string)

In [2]:
super_unlabled_positions = '''
  0.0000000000000000  0.0000000000000000  0.2500000000000000
  0.5000000000000000  0.5000000000000000  0.2500000000000000
  0.0000000000000000  0.0000000000000000  0.7500000000000000
  0.5000000000000000  0.5000000000000000  0.7500000000000000
  0.0000000000000000  0.0000000000000000  0.0000000000000000
  0.5000000000000000  0.5000000000000000  0.0000000000000000
  0.0000000000000000  0.0000000000000000  0.5000000000000000
  0.5000000000000000  0.5000000000000000  0.5000000000000000
  0.5000000000000000  0.0000000000000000  0.1002897284661302
  0.0000000000000000  0.5000000000000000  0.1002897284661302
  0.5000000000000000  0.0000000000000000  0.6002897284661373
  0.0000000000000000  0.5000000000000000  0.6002897284661373
  0.5000000000000000  0.0000000000000000  0.3997102565338650
  0.0000000000000000  0.5000000000000000  0.3997102565338650
  0.5000000000000000  0.0000000000000000  0.8997102565338650
  0.0000000000000000  0.5000000000000000  0.8997102565338650
  0.2500000000000000  0.7500000000000000  0.0804558199161249
  0.7500000000000000  0.2500000000000000  0.0804558199161249
  0.2500000000000000  0.7500000000000000  0.5804558199161249
  0.7500000000000000  0.2500000000000000  0.5804558199161249
  0.2500000000000000  0.7500000000000000  0.4195441800838751
  0.7500000000000000  0.2500000000000000  0.4195441800838751
  0.2500000000000000  0.7500000000000000  0.9195441800838751
  0.7500000000000000  0.2500000000000000  0.9195441800838751
  0.2500000000000000  0.2500000000000000  0.0804558199161249
  0.7500000000000000  0.7500000000000000  0.0804558199161249
  0.2500000000000000  0.2500000000000000  0.5804558199161249
  0.7500000000000000  0.7500000000000000  0.5804558199161249
  0.2500000000000000  0.2500000000000000  0.4195441800838751
  0.7500000000000000  0.7500000000000000  0.4195441800838751
  0.2500000000000000  0.2500000000000000  0.9195441800838751
  0.7500000000000000  0.7500000000000000  0.9195441800838751
  0.5000000000000000  0.0000000000000000  0.1808180868024820
  0.0000000000000000  0.5000000000000000  0.1808180868024820
  0.5000000000000000  0.0000000000000000  0.6808180868024820
  0.0000000000000000  0.5000000000000000  0.6808180868024820
  0.5000000000000000  0.0000000000000000  0.3191819281975157
  0.0000000000000000  0.5000000000000000  0.3191819281975157
  0.5000000000000000  0.0000000000000000  0.8191819281975157
  0.0000000000000000  0.5000000000000000  0.8191819281975157
  0.5000000000000000  0.0000000000000000  0.0000000000000000
  0.0000000000000000  0.5000000000000000  0.0000000000000000
  0.5000000000000000  0.0000000000000000  0.5000000000000000
  0.0000000000000000  0.5000000000000000  0.5000000000000000
'''
super_unlabled_positions =  string_to_matrix(super_unlabled_positions)

#Adding labeling matrix
Rb_array = np.array(['Rb'] * 4)
Nd_array = np.array(['Nd'] * 4)
Nb_array = np.array(['Nb'] * 8)
O_array = np.array(['O'] * 28)

# Concatenate the arrays to form the final vector
vector = np.concatenate((Rb_array, Nd_array, Nb_array, O_array))
# Reshape the vector to be a column vector
vector_column = vector.reshape(-1, 1)

# Add the vector as the first column of the matrix
super_labled_positions = np.hstack((vector_column, super_unlabled_positions))

In [3]:
super_lattice = '''
     5.4564043560499025    0.0000000000000000    0.0000000000000000
     0.0000000000000000    5.4564043560499025    0.0000000000000000
     0.0000000000000000    0.0000000000000000   22.2047033342644689
'''
super_lattice = string_to_matrix(super_lattice)

In [4]:
Imma_positions = '''    
  0.0000000000000000  0.0000000000000000  0.2500000000000000
  0.5000000000000000  0.5000000000000000  0.2500000000000000
  0.0000000000000000  0.0000000000000000  0.7500000000000000
  0.5000000000000000  0.5000000000000000  0.7500000000000000
  0.0000000000000000  0.0100898540040006  0.0000000000000000
  0.5000000000000000  0.4899101459959994  0.0000000000000000
  0.0000000000000000  0.9899101459959994  0.5000000000000000
  0.5000000000000000  0.5100898540040006  0.5000000000000000
  0.5000000000000000  0.9950691346854086  0.1011216350744633
  0.0000000000000000  0.5049308653145914  0.1011216350744633
  0.5000000000000000  0.0049308653145914  0.6011216350744704
  0.0000000000000000  0.4950691346854086  0.6011216350744704
  0.5000000000000000  0.0049308653145914  0.3988783499255319
  0.0000000000000000  0.4950691346854086  0.3988783499255319
  0.5000000000000000  0.9950691346854086  0.8988783499255319
  0.0000000000000000  0.5049308653145914  0.8988783499255319
  0.2500000000000000  0.7500000000000000  0.0707203686650644
  0.7500000000000000  0.2500000000000000  0.0946361184131703
  0.2500000000000000  0.7500000000000000  0.5946361184131703
  0.7500000000000000  0.2500000000000000  0.5707203686650644
  0.2500000000000000  0.7500000000000000  0.4053638815868297
  0.7500000000000000  0.2500000000000000  0.4292796313349356
  0.2500000000000000  0.7500000000000000  0.9292796313349356
  0.7500000000000000  0.2500000000000000  0.9053638815868297
  0.2500000000000000  0.2500000000000000  0.0946361184131703
  0.7500000000000000  0.7500000000000000  0.0707203686650644
  0.2500000000000000  0.2500000000000000  0.5707203686650644
  0.7500000000000000  0.7500000000000000  0.5946361184131703
  0.2500000000000000  0.2500000000000000  0.4292796313349356
  0.7500000000000000  0.7500000000000000  0.4053638815868297
  0.2500000000000000  0.2500000000000000  0.9053638815868297
  0.7500000000000000  0.7500000000000000  0.9292796313349356
  0.5000000000000000  0.9376345942216702  0.1809127204779060
  0.0000000000000000  0.5623654057783298  0.1809127204779060
  0.5000000000000000  0.0623654057783298  0.6809127204779131
  0.0000000000000000  0.4376345942216702  0.6809127204779131
  0.5000000000000000  0.0623654057783298  0.3190872945220917
  0.0000000000000000  0.4376345942216702  0.3190872945220917
  0.5000000000000000  0.9376345942216702  0.8190872945220846
  0.0000000000000000  0.5623654057783298  0.8190872945220846
  0.5000000000000000  0.0708445720799631  0.0000000000000000
  0.0000000000000000  0.4291554279200369  0.0000000000000000
  0.5000000000000000  0.9291554279200369  0.5000000000000000
  0.0000000000000000  0.5708445720799631  0.5000000000000000'''

super_unlabled_positions =  string_to_matrix(Imma_positions)

#Adding labeling matrix
Rb_array = np.array(['Rb'] * 4)
Nd_array = np.array(['Nd'] * 4)
Nb_array = np.array(['Nb'] * 8)
O_array = np.array(['O'] * 28)

# Concatenate the arrays to form the final vector
vector = np.concatenate((Rb_array, Nd_array, Nb_array, O_array))
# Reshape the vector to be a column vector
vector_column = vector.reshape(-1, 1)

# Add the vector as the first column of the matrix
super_labled_positions = np.hstack((vector_column, super_unlabled_positions))

In [5]:
Imma_lattice = '''
     5.4336113551497656    0.0000000000000000    0.0000000000000000
     0.0000000000000000    5.5034279496786311    0.0000000000000000
     0.0000000000000000    0.0000000000000000   21.9556215042956495
     '''
super_lattice = string_to_matrix(Imma_lattice)

In [6]:
import re

def select_modes_by_header(filename, pattern, columns_to_remove=None):
    with open(filename, 'r') as file:
        input_data = file.read()
    
    data_arrays = []
    pattern_regex = re.compile(pattern)
    
    # Split the input data into individual arrays
    arrays = input_data.strip().split('\n\n')

    for array in arrays:
        lines = array.split('\n')

        # Check if the header matches the pattern
        header = lines[0]
        if not pattern_regex.search(header):
            continue
        
        # Remove the first line (header)
        lines.pop(0)

        data = []
        for line in lines:
            if line.strip():  # Check if the line is not empty
                components = line.split()
                # Skip the first component and convert the rest to floats
                row = [components[0]] + [float(component) for component in components[1:]]
                
                data.append(row)

        # Remove specific columns if specified
        if columns_to_remove:
            for row in data:
                for col_index in sorted(columns_to_remove, reverse=True):
                    # Adjusted to account for the skipped first column
                    if col_index != 0:
                        del row[col_index]

        # Construct the data array dictionary
        data_arrays.append({'header': header, 'data': data})

    return data_arrays

def select_modes_by_header(filename, pattern, columns_to_remove=None):
    """ Extracts data sections from a file based on header matching a regex pattern.
    
    Args:
        filename (str): The path to the input file.
        pattern (str): Regex pattern to match in the headers.
        columns_to_remove (list of int, optional): Indices of columns to remove from the data, excluding the first column.
    
    Returns:
        list of dict: List of dictionaries containing the header and data of matching sections.
    """
    pattern_regex = re.compile(pattern)
    data_arrays = []
    
    try:
        with open(filename, 'r') as file:
            current_section = []
            include_section = False
            
            for line in file:
                line = line.strip()
                if not line:  # Empty line signifies end of a section
                    if include_section and current_section:
                        data_arrays.append(process_section(current_section, columns_to_remove))
                    current_section = []
                    include_section = False
                else:
                    if not current_section:  # This means we're at the header
                        include_section = bool(pattern_regex.search(line))
                    current_section.append(line)
                    
            # Handle the last section if file does not end with a newline
            if include_section and current_section:
                data_arrays.append(process_section(current_section, columns_to_remove))
    
    except IOError as e:
        print(f"Error reading file: {e}")
        return []
    
    return data_arrays

def process_section(section, columns_to_remove):
    """ Processes a section, removing specified columns and converting data to float. """
    header = section[0]
    data = []
    for line in section[1:]:
        components = line.split()
        if columns_to_remove:
            row = [components[i] for i in range(len(components)) if i not in columns_to_remove]
        else:
            row = components
        data.append([float(x) if i > 0 else x for i, x in enumerate(row)])  # Convert all but first component to float
    return {'header': header, 'data': data}

# Example usage
# result = select_modes_by_header('./ISODISTORT_NaNNO_2x2x2.txt', r'\]R3\+\(', [1,2,3])


In [53]:
def add_distortions_by_labels(matrix1, matrix2, lattice_basis):
    """
    Adds distortions to rows in matrix1 based on corresponding rows in matrix2.
    Args:
    - matrix1: Original positions to be distorted, labled with numbers to match each mode to each atom exactly
    - matrix2: SAM distortions with labels
    - lattice_basis: Lattice constants of the supercell
    Returns:
    - result_matrix: Matrix1 with distortions added
    """
    matrix_copy = np.copy(matrix1[:, 1:].astype(float))

    # Convert matrix2 to Cartesian coordinates
    cartesian_matrix2 = np.dot(matrix2[:, 1:].astype(float), lattice_basis)

    # Normalize matrix in cartesian: MODE AMOUNTS TO 1Ang
    normalized_matrix2 = cartesian_matrix2 / np.linalg.norm(cartesian_matrix2)

    inverse_t = np.linalg.inv(lattice_basis)
    
    #bring matrix back to direct
    direct_normalized = np.dot(normalized_matrix2,inverse_t)

    for row, normalized_row in zip(matrix2, direct_normalized):
        label = row[0]
        for i, row1 in enumerate(matrix1):
            if row1[0] == label:
                distortion = normalized_row * 0.001 #1mAng distortion
                matrix_copy[i] += distortion

    return np.hstack((matrix1[:, :1], matrix_copy))

def add_numbers2labels(data):
    data = np.array(data)
    # Dictionary to keep track of label counts
    label_counts = {}
    # Iterate through the array and append numbers to labels
    for i, row in enumerate(data):
        label = row[0]
        if label not in label_counts:
            label_counts[label] = 1
        else:
            label_counts[label] += 1
        data[i][0] = f"{label}{label_counts[label]}"
    return data


# Process the data with specified columns to remove
result = select_modes_by_header('/Users/brunobanas/Documents/Cornell/Thesis/RbNdNb2O7/ISODISTORT_SAMs_r2xr2x2.txt', r'\]A2\+\(', [1,2,3])

#print(result)
#print(result[-1]['data'])
#result = select_modes_by_header('./ISODISTORT_NaNNO_2x2x2.txt', r'\]X4\-\(', [1,2,3])
#print(result[-1]['data'])

for i in range(len(result)):
    moded_matrix = add_distortions_by_labels(np.array([row[:] for row in add_numbers2labels(super_labled_positions)]), np.array(result[i]['data']), super_lattice) #labled matrix had columns of strings - convert to float    

    formatted_unlabeled = matrix_to_string(moded_matrix[:,1:].astype(float))# + A5minus_dist*0.1)#+ GM5minus_eigenvec*0.1)# + A5minus_dist*0.1)
    print(formatted_unlabeled, '\n')
    #print(formatted_labeled)

0.0000000000000000 0.0000000000000000 0.2500000000000000
0.5000000000000000 0.5000000000000000 0.2500000000000000
0.0000000000000000 0.0000000000000000 0.7500000000000000
0.5000000000000000 0.5000000000000000 0.7500000000000000
0.0000000000000000 0.0100898540040006 0.0000000000000000
0.5000000000000000 0.4899101459959994 0.0000000000000000
0.0000000000000000 0.9899101459959994 0.5000000000000000
0.5000000000000000 0.5100898540040006 0.5000000000000000
0.5000000000000000 0.9950691346854086 0.1011216350744633
0.0000000000000000 0.5049308653145914 0.1011216350744633
0.5000000000000000 0.0049308653145914 0.6011216350744704
0.0000000000000000 0.4950691346854086 0.6011216350744704
0.5000000000000000 0.0049308653145914 0.3988783499255319
0.0000000000000000 0.4950691346854086 0.3988783499255319
0.5000000000000000 0.9950691346854086 0.8988783499255319
0.0000000000000000 0.5049308653145914 0.8988783499255319
0.2500323255844176 0.7499676744155824 0.0707203686650644
0.7499676744155824 0.2500323255

### SAMs

In [54]:
def Make_SAMs(positions, ISOMODE, lattice_basis):

    # Convert ISOMODE to Cartesian coordinates
    cartesian_matrix2 = np.dot(ISOMODE[:, 1:].astype(float), lattice_basis)

    # Normalize entire ISOMODE   
    normalized_matrix2 = cartesian_matrix2 / np.linalg.norm(cartesian_matrix2)#, axis=1)[:, np.newaxis]

    shape_matrix1 = positions[:, 1:].astype(float).shape
    # Create a new empty matrix of the same shape as positions
    empty_matrix_pos = np.zeros(shape_matrix1)

    for row, normalized_row in zip(ISOMODE, normalized_matrix2):
        label = row[0]
        for i, row1 in enumerate(positions):
            if row1[0] == label:
                empty_matrix_pos[i] += normalized_row
                
    return empty_matrix_pos #np.hstack((matrix1[:, :1], matrix_copy))

# Process the data with specified columns to remove
#result = select_modes_by_header('./ISODISTORT_NHNNO_r2xr2x2.txt', r']A5', [1,2,3])
SAM_modes = []
for i in range(len(result)):
    
    numbered_positions = np.array([row[:] for row in add_numbers2labels(super_labled_positions)])

    ith_mode = np.array(result[i]['data'])

    moded_matrix = Make_SAMs(numbered_positions, ith_mode, super_lattice) #labled matrix had columns of strings - convert to float    
    #    moded_matrix = add_distortions_by_labels(moded_matrix, np.array(result[i+1]['data']),lattice_basis)
    SAM_modes.append(moded_matrix)
    formatted_unlabeled = matrix_to_string(moded_matrix[:,:])
    print(formatted_unlabeled, '\n')

0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.0000000000000000 0.0000000000000000 0.0000000000000000
0.1756446625530246 -0.1779015247732130 0.0000000000000000
-0.1756446625530246 0.17790152

### Make mode_masses

In [41]:
elements = {
    'Na': 22.989769,
    'Nd': 144.242,
    'Nb': 92.90638,
    'O': 15.9994
}
elements = {
    'Nd': 144.242,
    'Nb': 92.90638,
    'O': 15.9994,
    'N1': 14.0067,
    'H': 1
}
elements = {
    'Rb': 85.468,
    'Nd': 144.242,
    'Nb': 92.90638,
    'O': 15.9994
}
# Process the data with specified columns to remove
#result = select_modes_by_header('./ISODISTORT_NHNNO_r2xr2x2.txt', r']A5', [1,2,3])
mode_masses = []
# Iterate over each section of the data
for section in result:
    # Flatten the list of lists into a single list
    flattened_section = [element for sublist in section['data'] for element in sublist if isinstance(element, str)]
    
    # Check for each pattern in the current flattened section
    for pattern, mass in elements.items():
        if any(re.search(pattern, element) for element in flattened_section):
            mode_masses.append(mass)


for number in mode_masses:
    print(number)

15.9994


### Combining eigenvectors and changing direction

Do dot product of eigenvec with SAMs, half of the SAMs should have ~0 contributions (0A direction) while other half have non-zero (A0 direction). 

In [42]:
eigenvec = '''  
0 0 0
0 0 0
0 0 0
0 0 0
3.544201159066991e-13 0.2046884085500781 0
-3.544201159066991e-13 -0.2046884085500781 0
-3.544201159066991e-13 -0.2046884085500781 0
3.544201159066991e-13 0.2046884085500781 0
4.452156015802587e-14 -0.02574395460402027 0
-4.452156015802587e-14 0.02574395460402027 0
-4.452156015802587e-14 0.02574395460402027 0
4.452156015802587e-14 -0.02574395460402027 0
-4.452156015802587e-14 0.02574395460402027 0
4.452156015802587e-14 -0.02574395460402027 0
4.452156015802587e-14 -0.02574395460402027 0
-4.452156015802587e-14 0.02574395460402027 0
0 0 -0.1330297065647695
0 0 0.1330297065647695
0 0 0.1330297065647695
0 0 -0.1330297065647695
0 0 -0.1330297065647695
0 0 0.1330297065647695
0 0 0.1330297065647695
0 0 -0.1330297065647695
0 0 0.1330297065652302
0 0 -0.1330297065652302
0 0 -0.1330297065652302
0 0 0.1330297065652302
0 0 0.1330297065652302
0 0 -0.1330297065652302
0 0 -0.1330297065652302
0 0 0.1330297065652302
1.327673827921325e-13 -0.07676728243731851 0
-1.327673827921325e-13 0.07676728243731851 0
-1.327673827921325e-13 0.07676728243731851 0
1.327673827921325e-13 -0.07676728243731851 0
-1.327673827921325e-13 0.07676728243731851 0
1.327673827921325e-13 -0.07676728243731851 0
1.327673827921325e-13 -0.07676728243731851 0
-1.327673827921325e-13 0.07676728243731851 0
-6.103950664701034e-13 0.3524246166022268 0
6.103950664701034e-13 -0.3524246166022268 0
6.103950664701034e-13 -0.3524246166022268 0
-6.103950664701034e-13 0.3524246166022268 0
'''
eigenvec = string_to_matrix(eigenvec)

print(matrix_to_string(eigenvec*0.01+super_unlabled_positions))

0.0000000000000000 0.0000000000000000 0.2500000000000000
0.5000000000000000 0.5000000000000000 0.2500000000000000
0.0000000000000000 0.0000000000000000 0.7500000000000000
0.5000000000000000 0.5000000000000000 0.7500000000000000
0.0000000000000035 0.0121367380895014 0.0000000000000000
0.4999999999999964 0.4878632619104986 0.0000000000000000
-0.0000000000000035 0.9878632619104986 0.5000000000000000
0.5000000000000036 0.5121367380895014 0.5000000000000000
0.5000000000000004 0.9948116951393684 0.1011216350744633
-0.0000000000000004 0.5051883048606316 0.1011216350744633
0.4999999999999996 0.0051883048606316 0.6011216350744704
0.0000000000000004 0.4948116951393684 0.6011216350744704
0.4999999999999996 0.0051883048606316 0.3988783499255319
0.0000000000000004 0.4948116951393684 0.3988783499255319
0.5000000000000004 0.9948116951393684 0.8988783499255319
-0.0000000000000004 0.5051883048606316 0.8988783499255319
0.2500000000000000 0.7500000000000000 0.0693900715994167
0.7500000000000000 0.2500000

In [43]:
A0mode = []
OAmode = []
for i in range(len(SAM_modes)):
    
    weights = np.dot(SAM_modes[i].flatten(), eigenvec.flatten())
    #print(weights)
    if weights > 0.0001 or weights<-0.0001:
        #print(i)
        A0mode.append(np.dot(weights, SAM_modes[i]))
        OAmode.append(np.dot(weights, SAM_modes[i-1]))


A0mode = np.sum(np.array(A0mode), axis=0)
add_mode_in_cart = A0mode*0.1 + np.dot(super_unlabled_positions, super_lattice)
print(matrix_to_string(np.dot(add_mode_in_cart, np.linalg.inv(super_lattice))))

OAmode = np.sum(np.array(OAmode), axis=0)
add_mode_in_cart = (OAmode+A0mode)*0.1 + np.dot(super_unlabled_positions, super_lattice)
print(matrix_to_string(np.dot(add_mode_in_cart, np.linalg.inv(super_lattice))))

0.0000000000000000 0.0000000000000000 0.2500000000000000
0.5000000000000000 0.5000000000000000 0.2500000000000000
0.0000000000000000 0.0000000000000000 0.7500000000000000
0.5000000000000000 0.5000000000000000 0.7500000000000000
0.0000000000000000 0.0100898540040006 0.0000000000000000
0.5000000000000000 0.4899101459959994 0.0000000000000000
0.0000000000000000 0.9899101459959994 0.5000000000000000
0.5000000000000000 0.5100898540040006 0.5000000000000000
0.5000000000000000 0.9950691346854085 0.1011216350744633
0.0000000000000000 0.5049308653145914 0.1011216350744633
0.5000000000000000 0.0049308653145914 0.6011216350744704
0.0000000000000000 0.4950691346854086 0.6011216350744704
0.5000000000000000 0.0049308653145914 0.3988783499255318
0.0000000000000000 0.4950691346854086 0.3988783499255318
0.5000000000000000 0.9950691346854085 0.8988783499255321
0.0000000000000000 0.5049308653145914 0.8988783499255321
0.2500000000000000 0.7500000000000000 0.0707203686650644
0.7500000000000000 0.2500000000

### Docomposition of low sym eigenvec wrt high sym SAM

\]GM1+\+\(
\]GM2\+\(


In [44]:
low_sym_GM2p = '''
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0 0 0
0.00846499179108556 0 0
0.00846499179108556 0 0
0.00846499179108556 0 0
0.00846499179108556 0 0
-0.00846499179108556 0 0
-0.00846499179108556 0 0
-0.00846499179108556 0 0
-0.00846499179108556 0 0
-0.06987826327714608 0.1047745683784608 0
0.2490468928732959 -0.2112658652326712 0
0.2490468928732959 -0.2112658652326712 0
-0.06987826327714608 0.1047745683784608 0
-0.2490468928732959 0.2112658652326712 0
0.06987826327714608 -0.1047745683784608 0
0.06987826327714608 -0.1047745683784608 0
-0.2490468928732959 0.2112658652326712 0
0.2490468928732959 0.2112658652326712 0
-0.06987826327714608 -0.1047745683784608 0
-0.06987826327714608 -0.1047745683784608 0
0.2490468928732959 0.2112658652326712 0
0.06987826327714608 0.1047745683784608 0
-0.2490468928732959 -0.2112658652326712 0
-0.2490468928732959 -0.2112658652326712 0
0.06987826327714608 0.1047745683784608 0
-0.04909217243208652 0 0
-0.04909217243208652 0 0
-0.04909217243208652 0 0
-0.04909217243208652 0 0
0.04909217243208652 0 0
0.04909217243208652 0 0
0.04909217243208652 0 0
0.04909217243208652 0 0
0 0 0
0 0 0
0 0 0
0 0 0
'''
low_sym_GM2p = string_to_matrix(low_sym_GM2p)

In [45]:
low_sym_GM3p = '''  
0 0 0
0 0 0
0 0 0
0 0 0
-0.1419862264333926 0 0
0.1419862264333926 0 0
0.1419862264333926 0 0
-0.1419862264333926 0 0
-0.01418536813411861 0 0
0.01418536813411861 0 0
0.01418536813411861 0 0
-0.01418536813411861 0 0
0.01418536813411861 0 0
-0.01418536813411861 0 0
-0.01418536813411861 0 0
0.01418536813411861 0 0
0 0 -0.08023236068872848
0 0 0.1931940356322623
0 0 0.1931940356322623
0 0 -0.08023236068872848
0 0 -0.1931940356322623
0 0 0.08023236068872848
0 0 0.08023236068872848
0 0 -0.1931940356322623
0 0 -0.1931940356322623
0 0 0.08023236068872848
0 0 0.08023236068872848
0 0 -0.1931940356322623
0 0 -0.08023236068872848
0 0 0.1931940356322623
0 0 0.1931940356322623
0 0 -0.08023236068872848
-0.1091343333118703 0 0
0.1091343333118703 0 0
0.1091343333118703 0 0
-0.1091343333118703 0 0
0.1091343333118703 0 0
-0.1091343333118703 0 0
-0.1091343333118703 0 0
0.1091343333118703 0 0
0.3436488360798268 0 0
-0.3436488360798268 0 0
-0.3436488360798268 0 0
0.3436488360798268 0 0
'''
low_sym_GM3p = string_to_matrix(low_sym_GM3p)

In [46]:
low_sym_GM4m = '''
-0.02324531785982561 0 0
-0.02324531785982561 0 0
-0.02324531785982561 0 0
-0.02324531785982561 0 0
-0.2148213108304049 0 0
-0.2148213108304049 0 0
-0.2148213108304049 0 0
-0.2148213108304049 0 0
-0.03526147705797023 0 0
-0.03526147705797023 0 0
-0.03526147705797023 0 0
-0.03526147705797023 0 0
-0.03526147705797023 0 0
-0.03526147705797023 0 0
-0.03526147705797023 0 0
-0.03526147705797023 0 0
-0.08859301933222358 0.1027532058169276 0
0.2010038042978296 -0.1788113319751307 0
0.2010038042978296 -0.1788113319751307 0
-0.08859301933222358 0.1027532058169276 0
0.2010038042978296 -0.1788113319751307 0
-0.08859301933222358 0.1027532058169276 0
-0.08859301933222358 0.1027532058169276 0
0.2010038042978296 -0.1788113319751307 0
0.2010038042978296 0.1788113319751307 0
-0.08859301933222358 -0.1027532058169276 0
-0.08859301933222358 -0.1027532058169276 0
0.2010038042978296 0.1788113319751307 0
-0.08859301933222358 -0.1027532058169276 0
0.2010038042978296 0.1788113319751307 0
0.2010038042978296 0.1788113319751307 0
-0.08859301933222358 -0.1027532058169276 0
-0.02473175672213751 0 0
-0.02473175672213751 0 0
-0.02473175672213751 0 0
-0.02473175672213751 0 0
-0.02473175672213751 0 0
-0.02473175672213751 0 0
-0.02473175672213751 0 0
-0.02473175672213751 0 0
0.134296180775942 0 0
0.134296180775942 0 0
0.134296180775942 0 0
0.134296180775942 0 0
'''
low_sym_GM4m = string_to_matrix(low_sym_GM4m)

low_sym_lattice = '''
     5.4336113551497656    0.0000000000000000    0.0000000000000000
     0.0000000000000000    5.5034279496786311    0.0000000000000000
     0.0000000000000000    0.0000000000000000   21.9556215042956495
'''
low_sym_lattice = string_to_matrix(low_sym_lattice)

low_sym_cart = np.dot(low_sym_GM4m, low_sym_lattice)

In [47]:
cart_unlabled_positions = np.dot(super_unlabled_positions, super_lattice)
distorion = low_sym_cart-cart_unlabled_positions
print(distorion)

[[ -0.12630602   0.          -5.48890538]
 [ -2.8431117   -2.75171397  -5.48890538]
 [ -0.12630602   0.         -16.46671613]
 [ -2.8431117   -2.75171397 -16.46671613]
 [ -1.16725551  -0.05552878   0.        ]
 [ -3.88406119  -2.69618519   0.        ]
 [ -1.16725551  -5.44789917 -10.97781075]
 [ -3.88406119  -2.80724276 -10.97781075]
 [ -2.90840284  -5.47629129  -2.22018835]
 [ -0.19159716  -2.77885064  -2.22018835]
 [ -2.90840284  -0.02713666 -13.1979991 ]
 [ -0.19159716  -2.72457731 -13.1979991 ]
 [ -2.90840284  -0.02713666  -8.75762208]
 [ -0.19159716  -2.72457731  -8.75762208]
 [ -2.90840284  -5.47629129 -19.73543283]
 [ -0.19159716  -2.77885064 -19.73543283]
 [ -1.83978287  -3.5620761   -1.55270965]
 [ -2.98303196  -2.35993227  -2.0777948 ]
 [ -0.26622629  -5.11164624 -13.05560555]
 [ -4.55658855  -0.81036212 -12.5305204 ]
 [ -0.26622629  -5.11164624  -8.90001596]
 [ -4.55658855  -0.81036212  -9.42510111]
 [ -1.83978287  -3.5620761  -20.40291186]
 [ -2.98303196  -2.35993227 -19.87

In [63]:
def Make_SAMs(positions, ISOMODE, lattice_basis):

    # Convert ISOMODE to Cartesian coordinates
    cartesian_matrix2 = np.dot(ISOMODE[:, 1:].astype(float), lattice_basis)

    # Normalize entire ISOMODE   
    normalized_matrix2 = cartesian_matrix2 / np.linalg.norm(cartesian_matrix2)#, axis=1)[:, np.newaxis]

    shape_matrix1 = positions[:, 1:].astype(float).shape
    # Create a new empty matrix of the same shape as positions
    empty_matrix_pos = np.zeros(shape_matrix1)

    for row, normalized_row in zip(ISOMODE, normalized_matrix2):
        label = row[0]
        for i, row1 in enumerate(positions):
            if row1[0] == label:
                empty_matrix_pos[i] += normalized_row
                
    return empty_matrix_pos #np.hstack((matrix1[:, :1], matrix_copy))
for irrep in [r'\]GM1+\(', r'\]GM2\+\(', r'\]GM5\+\(', r'\]GM3\-\(', r'\]GM4\-\(', r'\]GM5\-\(', 
              r'\]M1\+\(', r'\]M2\+\(', r'\]M3\+\(', r'\]M4\+\(', r'\]M5\+\(', r'\]M1\-\(', r'\]M2\-\(', r'\]M3\-\(', r'\]M4\-\(', r'\]M5\-\(', 
              r'\]A1\+\(', r'\]A2\+\(', r'\]A3\+\(', r'\]A4\+\(', r'\]A5\+\(', r'\]A1\-\(', r'\]A2\-\(', r'\]A3\-\(', r'\]A4\-\(', r'\]A5\-\(',
              r'\]Z1\+\(', r'\]Z2\+\(', r'\]Z3\+\(', r'\]Z4\+\(', r'\]Z5\+\(', r'\]Z1\-\(', r'\]Z2\-\(', r'\]Z3\-\(', r'\]Z4\-\(', r'\]Z5\-\(']:
    # Process the data with specified columns to remove
    result = select_modes_by_header('/Users/brunobanas/Documents/Cornell/Thesis/RbNdNb2O7/ISODISTORT_SAMs_r2xr2x2.txt', irrep, [1,2,3])
    #result = select_modes_by_header('./ISODISTORT_NHNNO_r2xr2x2.txt', r']A5', [1,2,3])
    SAM_modes = []
    for i in range(len(result)):
        
        numbered_positions = np.array([row[:] for row in add_numbers2labels(super_labled_positions)])

        ith_mode = np.array(result[i]['data'])

        moded_matrix = Make_SAMs(numbered_positions, ith_mode, super_lattice) #labled matrix had columns of strings - convert to float    
        #    moded_matrix = add_distortions_by_labels(moded_matrix, np.array(result[i+1]['data']),lattice_basis)
        SAM_modes.append(moded_matrix)
        formatted_unlabeled = matrix_to_string(moded_matrix[:,:])
        #print(formatted_unlabeled, '\n')
    
    weights = []
    for i in range(len(SAM_modes)):
    
        weight = np.dot(SAM_modes[i].flatten(), low_sym_GM3p.flatten())
        if abs(weight)>0.01:
            weights.append(weight)
    print(irrep, weights)

\]GM1+\( []
\]GM2\+\( [0.22592334988706766]
\]GM5\+\( []
\]GM3\-\( []
\]GM4\-\( []
\]GM5\-\( []
\]M1\+\( []
\]M2\+\( []
\]M3\+\( []
\]M4\+\( []
\]M5\+\( []
\]M1\-\( []
\]M2\-\( []
\]M3\-\( []
\]M4\-\( []
\]M5\-\( []
\]A1\+\( []
\]A2\+\( []
\]A3\+\( []
\]A4\+\( []
\]A5\+\( []
\]A1\-\( []
\]A2\-\( []
\]A3\-\( []
\]A4\-\( []
\]A5\-\( [-0.2839724528667852, 0.04012228000505133, 0.5468527926419816, 0.30867850858038565, -0.6872976721596536]
\]Z1\+\( []
\]Z2\+\( []
\]Z3\+\( []
\]Z4\+\( []
\]Z5\+\( []
\]Z1\-\( []
\]Z2\-\( []
\]Z3\-\( []
\]Z4\-\( []
\]Z5\-\( []


In [60]:
weights = []
for i in range(len(SAM_modes)):
    
    weight = np.dot(SAM_modes[i].flatten(), low_sym_GM4m.flatten())
    weights.append(weight)
    if abs(weight)>0.01:
            weights.append(weight)
print(weights)
weights = weights/np.linalg.norm(weights)
print(weights)
np.sum(weights**2)


[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.938893903907228e-18, 0.0, 0.0, 0.0, 0.0, 0.0]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


1.0